name: matrix_input
description: A package that leverages on the power of flutter widgets to display data in matrix form.
version: 1.1.0
homepage: https://github.com/Ndinyo/matrix_input

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
