name: matrix_input
description: A package that leverages on the power of flutter widgets to display data in matrix form.
version: 1.2.0
homepage: https://github.com/Ndinyo/matrix_input

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.7


# The following section is specific to Flutter.
flutter:
